travis:
  secure:
    BINSTAR_TOKEN: 4rrBlGneF0DMH5+lG6Prd2cubVo49Hfe7vtMTGGTKs0I87eALUZ5lDelJ6OyBpt/gF4uO/YJkXRykX19gPqPw1mw7i/nbuRwg0hQSO901rAF6fWgO23u7+uUbUaoKsIp6+yBAKK8oNFm4hhV9DN9AvI5nUNvM9uiuayXTtMUlwCIs+QTf1yMXJzRQ9DlN92BfvQchphW7oXtYYfCnQBA4kQdIHwCLjqnqm+zPDW1u7fillO+IgLW2RMhPQZyjKkpUnSf/KybGzBdVoJl1otbbJxYh4TprrytMNUTlbbmaiQ4b3oSH0+oBJlectntApQh1Hg1WdrJHkMTO5quYmghx6pTaAgqqCCEA4JWIJU5gjC5IxfqbUSPDNXlEKJLcqBeFkCB6oJkKLqE/X9j8NkyP6EWm5qra23FDkn4OphV8zm6PWpLeJyu7OoOW9AYpAVP4txh6Ilpl+dVSGtCuOdStWWwQBsBiGM4tf48hgbNnViS2Nic0Cp4NTroXE4y5wngLpXm4Yq+uCM3+VdMl76nkoVrYVrrZPDU4xrS8AZJkgGepe6NCUEldmpycCSKSxw9p2af6Gd/5pF5kRNTyaWmtiP2s54M4OFbh8dPPP4aanfC/mRGKME78RMRvHcL2WPxgzJRwgK9AEWEiD8MhLzFx22o9KASTCPumvbWr2AC3yI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
