travis:
  secure:
    BINSTAR_TOKEN: g2zn7BMyVD+K2HlxsCKEfNg7q2VT1nJEP/kF0z0IO14HOKcqI8T419SDl5Ug09v9odanZh+AtL5K8mfKl0gipjAJZ9ThkJONgEJoxKjAxSUqRlUECQXsX60QhvlJ0AIW3962lOiB9jQq6M5+RKZmSRyWxUBwx0xk692Z2GqkMVzoY4uuwk4+uQyxA0rFshFhtPUJcsHw5zkMsjzp7NfjeWzl9T5d5WxJwI/7+BhVQeBtT+SHeKAjyrkiY+sdhTdiuwQyuHyXmWfLWiPX2sCNMYkaGxwqUjP2ya9BuS2bsmmJcqvPjNwkdzsKtxajr4pWgTVteDhfgygd1/JqVrCm0dvmApQ/vA9JO48GWSJei0q+gRdex5y14n3LqgV5arQSf5oxV3bQ3Uyxt0sqabXPbUlL2+w1FIkrCwjv6A9xO9tmjwClB3AvyFUVRRPbtYQU7z7mWpgRmZoGN6WzeTRZwjozEnGBwmqCTzfdv6U4BkR1euimB4ApdCfYoSF/eImm6bsq8iLAk78aPJYVAhNLMO0x5NTTiASQGoBnVGFXbcme3XaDpN3erf8ttlJfjS4Yz1fw0sA3Ebq6IbgkXNigJ5EQK0MDxRl8yMPIKQKOR2fkhkdN3pWLl2EhjluIH8pKJih2aZQhwKloNVHUAeG4k/3Mxn912KMy+RUaRjvZrfU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
